Algoritmo "Repita"

//Repita usa a mesma lógia do enquanto a diferença é que o enquanto antes de
//rodar faz uma chegagem, o repita executa primeiramente 1 lógica de programação
//e depois faz a checagem para verificar se é para fazer o looping novamente
//O REPITA É IDEAL PARA A CRIAÇÃO DE MENUS, o repita é um pouco melhor em alguns casos
//porém o enquanto é mais poderoso por fazer a checagem previamente
//o enquanto é como se fosse um se que roda várias vezes
//enquanto = while
//repite = do while

Var

i : inteiro

Inicio

i <- 0

repita
Escreval(i)
i <- i + 1

ate i > 10


Fimalgoritmo