Algoritmo "Comando Para(para i de x ate y fimpara)"

Var
// melhor amigo pra trabalhar com vetor, funcoes, procedimentos, bando de dados
// para + vetor
//USAR O PARA SEMPRE QUE SOUBER OS VALORES CONSTANTES
//ENQUANTO E REPITA QUANDO TIVER UM BLOCO DE CÓDIGO QUE VC NÃO TEM IDEIA QUANTAS VEZES
//VAI REPETIR É ATÉ O USUÁRIO DAR A FLAG DE SAÍDA

i : inteiro


Inicio

//duas formas de fazer de 1 a 10

i <- 0

enquanto i <= 10 faca
         Escreval(i)
         i <- i + 1
fimenquanto

repita
      Escreval(i)
      i <- i + 1
até i > 10

para i de 1 ate 10 faca
     Escreval(i)
     se i = 6 entao
        Escreval(i)
        interrompa
     fimse
fimpara

para i de 30 ate 50 faca
     se i % 2 = 0 entao
        Escreval(i)
     fimse
fimpara



Fimalgoritmo