Algoritmo "Comando aleatório"
//serve para sortear um número que tenha começo e fim
Var
i, aleatorioMaximo, aleatorioMinimo, incremento : inteiro


Inicio

repita
aleatorio 1,100
leia(aleatorioMaximo)
leia(aleatorioMinimo)
aleatorio off
ate aleatorioMaximo >= aleatorioMinimo
limpatela

aleatorio 1,5
leia(incremento)
aleatorio off
limpatela

para i de aleatorioMinimo ate aleatorioMaximo passo incremento faca
     Escreval(i)
fimpara

Fimalgoritmo