algoritmo "Trabalhando com Tipos"
// Função :
// Autor :
// Data : 20/08/2022
// Seção de Declarações 
var
   numero1, numero2, subtracao, multiplicacao, soma: inteiro
   divisao: real
   sucesso: logico

inicio
// Seção de Comandos 
   Escreval("N1")
   leia(numero1)
   sucesso <- numero1 > 10
   Escreval(sucesso)
   //Escreval("N2")
   //leia(numero2)
   //soma <- numero1 + numero2
   //subtracao <- numero1 - numero2
   //multiplicacao <- numero1 * numero2
   //divisao <- numero1 / numero2
   
fimalgoritmo
