Algoritmo "Trabalhando com Tipos de Variáveis"

Var
// Seção de Declarações das variáveis
      nome, sobrenome, nomeCompleto: literal
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Informe o seu nome: ")
   leia(nome)
   Escreval("Informe o seu sobrenome: ")
   leia(sobrenome)
   nomeCompleto <- nome + " " + sobrenome
   Escreval(nomeCompleto)



Fimalgoritmo
